### ISSUE TITLE
Import template fail

### ISSUE THREAD

**Issue by marcelocluz** [barbosm/fortinet-zabbix#13]
Trying to import to a Zabbix appliance 4.4 and got the error bellow:

Cannot read XML: (41) Specification mandates value for attribute data-pjax-transient [Line: 53 | Column: 69].

**Comment by barbosm** [comment]
https://webapps.stackexchange.com/questions/87954/how-do-i-download-a-particular-file-from-github

Go to RAW, download or copy paste into editor and create the XML file. Right clicking on the file and saving it what caused the issue.
