### ISSUE TITLE
Import Zabbix Template for Juniper SRX Firewalls

### ISSUE THREAD

**Issue by ZabbixMNUser** [barbosm/fortinet-zabbix#52]
I downloaded the Zabbix 6.0 file - template_juniper_srx_series.yaml.  When I imported template_juniper_srx_series.yaml into Zabbix, I de-selected all boxes for "Update Existing", I selected all boxes for "Create New' and I de-selected all boxes for "Deleted" as this is a new template that didn't come with Zabbix 6.0 that I want to use on our Juniper SRX Firewalls and I don't want anything updated or deleted from the existing Juniper EX template for our Juniper EX Switches that comes with Zabbix 6.0 as the Juniper EX template is working without any problems.  When I select "Import", Zabbix displays the following message...  Unable to parse at line 8 (near "<!DOCTYPE html>").  Do you or someone at Zabbix knows how to resolve this?

Regards,

**Comment by mbdraks** [comment]
@ZabbixMNUser This repo does not have any relation with Juniper templates nor the official Zabbix templates.
