### ISSUE TITLE
Generates Multiple Emails while arising a Problem

### ISSUE THREAD

**Issue by imi911** [barbosm/fortinet-zabbix#54]
Hi,
I hope you doing well.
Well i am using zabbix for Monitoring our network. Although i have downloaded the Foritnet-Zabbix Package from your GitHub Page to monitor different Protocols. The main issue is that when Problem Trigger e.g VPN Tunnel Down so it generates multiple email against this protocol after One Second, so this shouldn't happen. While Arising the problem it should send only one email which we have configured in Media Types. Regard to this i also set the Step Duration of 1h but it doesn't works. I am totally stuck in this. Also apply multiple method to resolve this issue but the Issue is still there. 
Please i need your help regarding this. I hope you may understand this issue.

I am attaching the screenshot for the reference.

![image](https://user-images.githubusercontent.com/130434789/231071602-9d7e57aa-633e-4e34-85f6-ddc22b489ffe.png)

In above image you can see that it generates multiple emails against this Protocol. You may also see the time 13:40:16-In this time period it generates 8 emails. Please help me.

**Comment by mbdraks** [comment]
@imi911 I don't think I will be able to assist in this case, seems to be more of a tuning on Zabbix side than something related to the template itself.

You may want to review this: https://bestmonitoringtools.com/zabbix-alerts-setup-zabbix-email-notifications-escalations/#b_How_to_configure_condition_based_notifications and the zabbix documentation on the matter.

Good luck!

**Comment by imi911** [comment]
Thanks. This article would help me. 👍
